@echo off
title College Attendance Tracker - Background Service
cd /d "C:\Users\tanzi\Downloads\college-attendance-dev\college-attendance-dev\"
echo Starting web application...
start "College Attendance - Web App" /min cmd /c "call start.bat"
echo Waiting for web app to initialize...
timeout /t 15 /nobreak >nul
echo Starting scraper service loop...
:scraper_loop
echo Running attendance scraper at %date% %time%...
node scripts\run-scraper.js
echo Scraper completed. Next run in 3 hours...
timeout /t 10800 /nobreak >nul
goto scraper_loop
